---
title: '2018-11-21'
output: html_document
---

```{r}
library(limma)
library(edgeR)
require(ggplot2)       ## for plotting
require(limma)         ## for differential gene expression analysis
require(data.table)    ## for fast importing and manipulating data tables
```


```{r}
1# Input raw data
rawdata <- fread("../sandbox/Ex009_reads_per_transcript_2017-10-18.txt", check.names = FALSE, stringsAsFactors = FALSE)  ## for the logical arguments, space are needed
head(rawdata, n=3L) ## view first 3 rows of data
tail(rawdata, n=5L) ## view last 5 rows of data
```

```{r}
2# coerce columns to do DEG analysis
pre <- as.data.frame.matrix(rawdata[,34:35])
treated <- as.data.frame.matrix(rawdata[,38:39])
genename <- as.data.frame.matrix(rawdata[,41])
trial <- cbind(pre,treated)
trial <- cbind(trial,genename)
write.table(trial,file = "Ex009.txt",sep="\t",row.names=FALSE, quote=FALSE) ## still don't know whether I need sep="\t" here, quote = FALSE means nothing is quoted
```

```{r}
3# normalization
rawdata <- fread("../sandbox/Ex009.txt", check.names = FALSE, stringsAsFactors = FALSE)
y<-DGEList(counts=rawdata[,1:4],genes=rawdata[,5])##small parentheses means function, [,]means lines or rows of matrix ##
y<-calcNormFactors(y) ##TMM normalization, based on the assumption that the majority of genes are not DEGs
plotMDS(y)
## calculate log transformed, normalized count
cpm.o <- cpm( y, normalized.lib.sizes = FALSE, log = FALSE) # unnormalized
cpm.n <- cpm(y,normalized.lib.sizes = TRUE,log= FALSE)#normalized
boxplot(cpm.o, outline= F)
boxplot(cpm.n, col="green",outline = F)
```

```{4}
5## create design matrix


```



