---
title: '2018-11-26'
output: html_document
---

```{r}
library(limma)
library(edgeR)
require(ggplot2)       ## for plotting
require(limma)         ## for differential gene expression analysis
require(data.table)    ## for fast importing and manipulating data tables
```


```{r}
1# Input raw data
rawdata <- fread("../sandbox/Ex009_reads_per_transcript_2017-10-18.txt", check.names = FALSE, stringsAsFactors = FALSE)  ## for the logical arguments, space are needed
head(rawdata, n=3L) ## view first 3 rows of data
tail(rawdata, n=5L) ## view last 5 rows of data
```

```{r}
2# coerce columns to do del80 DEG analysis
pre <- as.data.frame.matrix(rawdata[,32:33])
treated <- as.data.frame.matrix(cbind(rawdata[,12],rawdata[,24]))
genename <- as.data.frame.matrix(rawdata[,41])
trial <- cbind(genename,pre,treated)##cbind() could bind more than two colums together
write.table(trial,file = "Ex009-del80.txt",sep="\t",row.names=FALSE, quote=FALSE) ## still don't know whether I need sep="\t" here, quote = FALSE means nothing is quoted
```

```{r}
3# normalization
rawdata <- fread("../sandbox/Ex009-del80.txt", check.names = FALSE, stringsAsFactors = FALSE)
y<-DGEList(counts=rawdata[,2:5],genes=rawdata[,1])##small parentheses means function, [,]means lines or rows of matrix ##
y<-calcNormFactors(y) ##TMM normalization, based on the assumption that the majority of genes are not DEGs
plotMDS(y)
## calculate log transformed, normalized count
cpm.o <- cpm( y, normalized.lib.sizes = FALSE, log = FALSE) # unnormalized
cpm.o1 <- cpm( y, normalized.lib.sizes = FALSE, log = TRUE) # unnormalized, log transformed
cpm.n1 <- cpm(y,normalized.lib.sizes = TRUE,log= FALSE)#normalized
cpm.n <- cpm(y,normalized.lib.sizes = TRUE,log= TRUE)#normalized, log transformed
boxplot(cpm.o, outline= F)
boxplot(cpm.o1, col="blue",outline= F)
boxplot(cpm.n1, col="red",outline = F)
boxplot(cpm.n, col="green",outline = F)
cpm.n <- cbind(genename,cpm.n)
write.table(cpm.n1,file="TMMnorm-del80-nolog.txt",row.names=FALSE,sep="\t",quote=F)#normalized
write.table(cpm.n,file="TMMnorm-del80.txt",row.names=FALSE,sep="\t",quote=F)#normalized, log transformed
```

```{r}
5## create design matrix
eset <- read.table("TMMnorm-del80.txt", sep="\t",header = TRUE,row.names=1) ## why we need sep="\t",rownames=1 whether we have the first column for our row names, rather than included into the datafram, which could be no numeric.
condition=factor(c(rep("del80",2),rep("del80del4",2))) ##use c() here to combine arguments into a vector, factor() needs a vector of data
design<-model.matrix(~-1+condition) ##Do not understand ~-1+condition, the object used in model.matrix should be an appropriate class, will get a matrix after run this function 
colnames(design)<-c("del80","del80del4")
contrast.matrix<-makeContrasts(contrasts="del80del4-del80",levels=design)##construct a contrast matrix, contrasts:character vector specify contrasts, levels: character vector or factor naming the parameters of which contrasts are desired?
fit<-lmFit(eset,design)## fit linear model for each gene given a series of arrays;argument design: the design matrix of the microarray experiment, with rows corresponding to arrays and columns to coefficients to be estimated.
fit1<-contrasts.fit(fit,contrast.matrix)##Given a linear model fit to microarray data, compute estimated coefficients and standard errors for a given set of contrasts, argument contrasts: numeric matrix with rows corresponding to coefficients in fit and columns containing contrasts. May be a vector if there is only one contrast.
fit2<-eBayes(fit1)##Given a microarray linear model fit, compute moderated t-statistics, moderated F-statistic, and log-odds of differential expression by empirical Bayes moderation of the standard errors towards a common value.
dif<-topTable(fit2,coef="del80del4-del80",n=nrow(fit2),adjust="BH")##extract a table of the top-ranked genes from a linear model fit
genesymbol<-rownames(dif)
dif<-cbind(genesymbol,dif)
write.table(dif,file="probeid.Foldchange-del80.txt",sep='\t',quote=F,row.names=F)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
# 6.sreening diff probeid
dif2<-topTable(fit2,coef="del80del4-del80",n=nrow(fit2),lfc=log2(2),adjust="BH")## Extract a table of the top-ranked genes from a linear model fit. lcf: minimum absolute log2-fold-change required. topTable and topTableF include only genes with (at least one) absolute log-fold-changes greater than lfc.
dif3<-dif2[dif2[,"adj.P.Val"]<0.05,]
dif4<-dif2[dif2[,"P.Value"]<0.05,]
genesymbol3<-rownames(dif3)
genesymbol4<-rownames(dif4)
dif3<-cbind(genesymbol3,dif3)
dif4<-cbind(genesymbol4,dif4)
write.table(dif3,file="diff.probeid.del80-FDR-adj.p0.05.txt",sep='\t',quote=F,row.names=F)
write.table(dif4,file="diff.probeid.del80-FDR-p0.05.txt",sep='\t',quote=F,row.names=F)

# 7.exp for diff probeid
dif3$genesymbol<-rownames(dif3)
dif4$genesymbol<-rownames(dif4)
loc3<-match(dif3$genesymbol,rownames(eset))
loc4<-match(dif4$genesymbol,rownames(eset))
DEG_exp3<-eset[loc3,]
DEG_exp4<-eset[loc4,]
genesymbol3<-rownames(DEG_exp3)
genesymbol4<-rownames(DEG_exp4)
DEG_exp3<-cbind(genesymbol3,DEG_exp3)
DEG_exp4<-cbind(genesymbol4,DEG_exp4)
write.table(DEG_exp3,file="probeid.del80-FDR-adj.p0.05.exprs.txt",sep='\t',quote=F,row.names=F)
write.table(DEG_exp4,file="probeid.del80-FDR-p0.05.exprs.txt",sep='\t',quote=F,row.names=F)
```


```{r}
##8. plot pheatmap
#source("http://www.bioconductor.org/biocLite.R")
#biocLite("pheatmap")
library(pheatmap)
DEG_exp<-read.table("probeid.del80-FDR-adj.p0.05.exprs.txt",
                    sep='\t',header=T,row.names=1)
pdf(file="pheatmap-del80-adjp0.05.pdf",width=20,height=10)
pheatmap(DEG_exp,
         color=colorRampPalette(c("blue","white","orange"))(100),
         fontsize_row=30,
         fontsize_col=30,scale="row",
         border_color=NA,cluster_col = FALSE)
dev.off()
DEG_exp2<-read.table("probeid.del80-FDR-p0.05.exprs.txt",
                    sep='\t',header=T,row.names=1)
pdf(file="pheatmap-del80-p0.05.pdf",width=50,height=25)
pheatmap(DEG_exp2,
         color=colorRampPalette(c("blue","white","orange"))(100),
         fontsize_row=0.5,
         fontsize_col=0.5,scale="row",
         border_color=NA,cluster_col = FALSE)
dev.off()
##  In del80/del4, adj.p.val<0.05 
##  Upregulated gene: Utr2; down regulated genes: Pho84, SGA1, CAGL0M02871g, RAX2, CAGL0A01243g, CAGL0B02926g, PHO4, CAGL0M11660g, USV1 
```